    ORG 00H
    JMP INIT
    ORG 23H
    JMP INTERRUPT
    ORG 50H
INDEX REG R0
INIT:
    MOV SCON, #01010000B
    ANL PCON, #01111111B
    MOV IE, #10010000B
    MOV TMOD, #00100000B
    MOV TH1, #0F3H
    MOV INDEX, #0
KEY_PAD:
    MOV DPTR, #KEY1
    MOV P1, #7FH
    ACALL READ_KEY
    MOV DPTR, #KEY2
    MOV P1, #0BFH
    ACALL READ_KEY
    MOV DPTR, #KEY3
    MOV P1, #0DFH
    ACALL READ_KEY
    MOV DPTR, #KEY4
    MOV P1, #0EFH
    ACALL READ_KEY
    JMP KEY_PAD
READ_KEY:
    MOV INDEX, #0
    JNB P1.0, DEB1
    INC INDEX
    JNB P1.1, DEB2
    INC INDEX
    JNB P1.2, DEB3
    INC INDEX
    JNB P1.3, DEB4
    RET
DEB1:
    ACALL DELAY
    JB P1.0, READ_KEY
    JMP TEMP
DEB2:
    ACALL DELAY
    JB P1.1, READ_KEY
    JMP TEMP
DEB3:
    ACALL DELAY
    JB P1.2, READ_KEY
    JMP TEMP
DEB4:
    ACALL DELAY
    JB P1.3, READ_KEY
TEMP:
    JNB P1.0, $
    JNB P1.1, $
    JNB P1.2, $
    JNB P1.3, $
SEND:
    MOV A, INDEX
    MOVC A, @A+DPTR
    MOV SBUF, A
    RET
DELAY:
   MOV R6, #0AFH
DELAY1:
   MOV R7, #0AH
   DJNZ R7, $
   DJNZ R6, DELAY1
   RET
INTERRUPT:
    JNB TI, END_INTER
    CLR TI
END_INTER:
    CLR RI
    RETI
KEY1:
    DB "048C"
KEY2:
    DB "159D"
KEY3:
    DB "26AE"
KEY4:
    DB "37BF"
    END
